### PR TITLE
Ubuntu

### PR DESCRIPTION
**Pull request by nfosdick**
Updating core code to allow for ubuntu in the east1.

### CODE REVIEW

**Comment by ghost** [comment]
Can this be rebased to eliminate the duplicate commits and the cleanup commits?

**Comment by nfosdick** [comment]
You're breaking my heart costa.  Just kidding thanks for teaching me the flatten.

**Comment by ghost** [comment]
No problem @nfosdick , let me know if you need help with it, a clean Git tree is a happy Git tree.

**Review by ghost — APPROVED** [review]
Neat, looks good!

**Pull request merged**
